# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('html', models.TextField()),
                ('url', models.TextField()),
                ('is_read', models.BooleanField()),
                ('is_stared', models.BooleanField()),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('site_url', models.TextField()),
                ('last_updated_time', models.DateTimeField()),
                ('favicon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_data.Favicon')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_data.Group'),
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_data.Feed'),
        ),
    ]
