# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core_data.Feed'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='favicon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='core_data.Group'),
        ),
        migrations.DeleteModel(
            name='Favicon',
        ),
    ]
